services:
  - type: web
    name: codejoy
    env: node
    plan: free # or your preferred plan
    healthCheckPath: /api/auth/check
    
    # This section tells Render how to build your project
    buildCommand: |
      # 1. Install frontend dependencies and build it
      npm install --prefix ./authentication/frontend
      npm run build --prefix ./authentication/frontend
      
      # 2. Install backend dependencies
      npm install --prefix ./authentication/backend
      
    # This section tells Render how to start your server
    startCommand: "npm start --prefix ./authentication/backend"

    # Environment variables to be set in the Render dashboard
    envVars:
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: GOOGLE_API_KEY
        sync: false
      - key: NODE_ENV
        value: production
      - key: CLIENT_URL
        fromService:
          type: web
          name: codejoy
          property: url